"""Pydantic models for the Silpo MCP domain."""

from __future__ import annotations

from .base import SilpoModel
from .branch import (
    Address,
    AvailableDeliveryType,
    Branch,
    DeliveryType,
    GeoPoint,
    NovaPoshtaOffice,
    NovaPoshtaSettlement,
    TimeSlot,
)
from .cart import (
    CartItem,
    CartLineInput,
    CartLoyalty,
    CartSummary,
    CartTotals,
    CartUpdateResult,
    CartValidation,
    CreateShoppingCartResult,
    SilpoCart,
)
from .category import (
    CategoriesTree,
    Category,
    CategoryDetail,
    CategoryNode,
    Promotion,
)
from .order import (
    Certificate,
    Coupon,
    CouponDetail,
    CouponProgress,
    DeliveryAddress,
    FamilyMember,
    FoodRestrictions,
    LoyaltyInfo,
    OfflineReceipt,
    OfflineReceiptItem,
    OnlineOrder,
    OnlineOrderItem,
    OrderLine,
    PremiumSubscription,
    Profile,
    Promo,
    PromoCode,
    SubscriptionFeature,
)
from .product import (
    BatchProductResult,
    ProductBatchItem,
    ProductDetail,
    ProductMatch,
    ProductSearchResult,
    ProductSet,
    SilpoProduct,
)

__all__ = [
    "Address",
    "AvailableDeliveryType",
    "BatchProductResult",
    "Branch",
    "CartItem",
    "CartLineInput",
    "CartLoyalty",
    "CartSummary",
    "CartTotals",
    "CartUpdateResult",
    "CartValidation",
    "CategoriesTree",
    "Category",
    "CategoryDetail",
    "CategoryNode",
    "Certificate",
    "Coupon",
    "CouponDetail",
    "CouponProgress",
    "CreateShoppingCartResult",
    "DeliveryAddress",
    "DeliveryType",
    "FamilyMember",
    "FoodRestrictions",
    "GeoPoint",
    "LoyaltyInfo",
    "NovaPoshtaOffice",
    "NovaPoshtaSettlement",
    "OfflineReceipt",
    "OfflineReceiptItem",
    "OnlineOrder",
    "OnlineOrderItem",
    "OrderLine",
    "PremiumSubscription",
    "ProductBatchItem",
    "ProductDetail",
    "ProductMatch",
    "ProductSearchResult",
    "ProductSet",
    "Profile",
    "Promo",
    "PromoCode",
    "Promotion",
    "SilpoCart",
    "SilpoModel",
    "SilpoProduct",
    "SubscriptionFeature",
    "TimeSlot",
]
